input.onButtonPressed(Button.A, function () {
    basic.showString("RGB")
    SuperBit.RGB_Program().setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    SuperBit.RGB_Program().show()
    SuperBit.RGB_Program().setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
    SuperBit.RGB_Program().show()
    SuperBit.RGB_Program().setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    SuperBit.RGB_Program().show()
    SuperBit.RGB_Program().setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    SuperBit.RGB_Program().show()
    basic.pause(500)
    SuperBit.RGB_Program().showColor(neopixel.colors(NeoPixelColors.Black))
    SuperBit.RGB_Program().clear()
})
basic.showIcon(IconNames.Yes)
music.playSoundEffect(music.createSoundEffect(WaveShape.Sine, 5000, 0, 255, 0, 500, SoundExpressionEffect.None, InterpolationCurve.Linear), SoundExpressionPlayMode.UntilDone)
music.playMelody("B B C5 A F G E D ", 120)
SuperBit.RGB_Program().setBrightness(100)
